Kafka using
netcracker-education-center/node-server pull request #5
Opened 2021-04-21 20:04 UTC by MajorPayne36

Several issues have been resolved

2021-04-22 15:55 UTC, Fuzzzi requested changes

2021-04-22 15:55 UTC, Fuzzzi commented on routes/report.js
> +// }
вынеси это в отдельную ветку, не понесем это в мейн

2021-04-22 15:55 UTC, Fuzzzi commented on routes/request.js
> +        logger.info(`Enything went wrong while sending request. Current exception: ${e}`);
почему не еррор? плохо же если не получилось отправить сообщение

2021-04-22 15:55 UTC, Fuzzzi commented on routes/ws.js
> +        console.log('-------------------Sended msg: ' + JSON.stringify(msg));
зачем нам писать в консоль?
либо в лог, либо это не нужно вообще

2021-04-22 19:05 UTC, MajorPayne36 commented on routes/request.js
> +        logger.info(`Enything went wrong while sending request. Current exception: ${e}`);
Поменял

2021-04-22 19:06 UTC, MajorPayne36 commented on routes/ws.js
> +        console.log('-------------------Sended msg: ' + JSON.stringify(msg));
Уберал в новую ветку

2021-04-22 19:06 UTC, MajorPayne36 commented on routes/report.js
> +// }
вынес

2021-04-23 16:46 UTC, Fuzzzi approved these changes

2021-04-23 16:46 UTC, merged